export const QUERY_KEYS = {
  LEADS: 'leads',
  PROPERTIES: 'properties',
  TASKS: 'tasks',
  PROFILE: 'profile',
  GAMIFICATION_TASKS: 'gamifiedTasks',
  GAMIFICATION_STATS: 'gamifiedStats',
  DAILY_STATS: 'dailyStats',
  RESCUE_SESSION: 'rescueSession',
  PERSONAL_NOTES: 'personalNotes',
  PERSONAL_TASKS: 'personalTasks',
  COACH_INSIGHTS: 'coachInsights',
  REVENUE_STATS: 'revenueStats',
  MAP_PINS: 'mapPins',
  REGION_SCORES: 'regionScores',
  TEMPLATES: 'templates',
  BROKER_ACCOUNT: 'brokerAccount',
  EXTERNAL_LISTINGS: 'externalListings',
  DAILY_RADAR: 'dailyRadar',
  DASHBOARD_STATS: 'dashboardStats',
  FIELD_VISITS: 'fieldVisits',
  MISSED_OPPORTUNITIES: 'missedOpportunities',
  AI_COACH_INSIGHT: 'aiCoachInsight',
  CATEGORIES: 'categories',
} as const;
